export const GET_ALL_OFFERS = "OFFERS/GET_ALL";
export const GET_ALL_RESTURANTS = "RESTURANTS/GET_ALL";
export const GET_ALL_CART_PRODUCTS = "CART/GET_ALL_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "CART/ADD_PRODUCT";



